"""Domain models for a vendor claim (مطالبة) and its integrity review.

Deliberately ROLE-AGNOSTIC: the flow is modeled as review gates (stages), not
as job titles. The client's procedure (SP-01-04-05-02) and their recorded
walkthrough contradict each other on who creates/approves the COC, so gates
carry no owner until the client clarifies. A `role` can be attached to a gate
later without touching the pipeline.
"""

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


class ClaimType(str, Enum):
    periodic = "periodic"  # مستخلص دوري / جاري
    first = "first"  # دفعة أولى
    final = "final"  # مستخلص نهائي / دفعة نهائية


class ContractKind(str, Enum):
    """Decides which document evidences acceptance — the middle of the
    three-way match. Goods: the goods/product receipt. Works/projects: the
    Certificate of Completion (محضر الإنجاز). One acceptance document per
    contract kind; the ERP receipt posting is a cross-check, never a second
    acceptance."""

    goods = "goods"  # توريد
    works = "works"  # مشروع / أعمال / مخرجات


class Severity(str, Enum):
    ok = "ok"
    warn = "warn"
    fail = "fail"


class Verdict(str, Enum):
    approve = "approve"
    reject = "reject"
    needs_human = "needs_human"


class RuleSource(BaseModel):
    """Where a rule comes from — every finding cites its normative source.

    This citation trail is the audit-defensibility story: the year-end internal
    reviewer can trace each check to procedure, law, ZATCA spec, contract, or
    the client policy (POC-P01, not yet provided).
    """

    doc: str  # e.g. "SP-01-04-05-02", "ZATCA e-invoicing", "POC-P01", "contract"
    ref: str = ""  # step / article / clause


class BoqLine(BaseModel):
    item_code: str
    description_ar: str
    description_en: str = ""
    unit: str = ""
    unit_price: float
    quantity: float


class InvoiceLine(BaseModel):
    item_code: str
    description_ar: str
    unit_price: float
    quantity: float
    amount: float


class InvoiceDoc(BaseModel):
    """The vendor's tax invoice as extracted (mock: seeded; real: CU/LLM)."""

    invoice_no: str
    invoice_date: str = ""
    seller_name_ar: str = ""
    seller_vat_number: str = ""
    total_with_vat: float = 0.0
    vat_amount: float = 0.0
    vat_exempt: bool = False
    qr_payload: str = ""  # base64 TLV from the printed QR; "" = no QR found
    lines: list[InvoiceLine] = Field(default_factory=list)


class CocDoc(BaseModel):
    """محضر الإنجاز (Certificate of Completion) as generated by the ERP."""

    coc_no: str = ""
    coc_date: str = ""
    claim_amount: float = 0.0
    has_delay: bool | None = None  # هل هناك تأخير في تنفيذ الأعمال؟
    has_stoppage: bool | None = None  # هل يوجد إيقاف و إعادة استئناف؟
    has_observations: bool | None = None  # هل هناك ملاحظات على التنفيذ؟
    delay_days: int = 0


class ReceiptLine(BaseModel):
    item_code: str
    description_ar: str = ""
    quantity: float  # quantity accepted for this claim period


class ReceiptDoc(BaseModel):
    """إيصال استلام المنتجات — the D365 product receipt the procedure posts at
    SPM-PM01 §9.3 step 5. The middle document of the three-way match:
    contract/BoQ (agreed) ↔ receipt (received) ↔ invoice (billed)."""

    receipt_no: str = ""
    receipt_date: str = ""
    lines: list[ReceiptLine] = Field(default_factory=list)


class PenaltyTerm(BaseModel):
    """One penalty clause as PRINTED in the contract — extracted, never invented.

    Distinct from ``Penalty`` (the ERP record of penalties actually imposed):
    these are the contract's TERMS, the yardstick the final check measures the
    penalty record against. ``text_ar`` keeps the verbatim clause fragment so
    the UI can locate the evidence on the contract page."""

    kind: str = "delay"  # delay | other
    rate_percent: float = 0.0  # printed rate, e.g. 10.0 for "(10%)"
    per: str = ""  # day | week | "" (flat / cap-style, no time unit printed)
    basis: str = ""  # what the percentage applies to, as printed
    cap_percent: float = 0.0  # overall ceiling; 0 = none printed
    text_ar: str = ""  # verbatim clause fragment (evidence anchor)
    ref: str = ""  # article / clause number as printed, e.g. "٣.٣.١"
    page: int = 0  # 1-based page of the contract document; 0 = unknown


class ContractDoc(BaseModel):
    """Contract header as extracted from the contract / PO document."""

    contract_no: str = ""
    start_date: str = ""
    end_date: str = ""  # contractual completion / delivery date
    value_base: float = 0.0
    penalty_terms: list[PenaltyTerm] = Field(default_factory=list)


class Penalty(BaseModel):
    reason_ar: str
    amount: float
    date: str = ""


class ClaimFile(BaseModel):
    """A source document file as staged from the ERP attachments.

    ``path`` is relative to the project root. ``doc_type`` is a hint for the
    extractor (invoice | contract_boq | coc | delivery_note | other).
    """

    path: str
    doc_type: str = "other"


class DetectedAttachment(BaseModel):
    """One vendor-file / government document as identified at the pre-finance
    gate: GPT classifies the OCR text and lifts the identity fields (CR
    number, VAT number, reference no., dates); a filename heuristic backs it
    up so an upload never goes silently unclassified."""

    file_name: str
    doc_key: str  # a prefinance required-attachment key, or "other"
    fields: dict[str, str] = Field(default_factory=dict)  # cr_number, vat_number, ...


class ClaimDocuments(BaseModel):
    invoice: InvoiceDoc | None = None
    coc: CocDoc | None = None
    receipt: ReceiptDoc | None = None  # ERP-owned; None = not posted / not pulled
    boq: list[BoqLine] = Field(default_factory=list)
    contract: ContractDoc | None = None  # header of the contract/PO document
    penalties: list[Penalty] = Field(default_factory=list)
    attachments: list[str] = Field(default_factory=list)  # names as filed in ERP
    # Filled by the guided intake when the reviewer uploads the vendor-file
    # documents; ERP-sourced claims carry only the `attachments` name list.
    detected_attachments: list[DetectedAttachment] = Field(default_factory=list)


class Claim(BaseModel):
    """One مطالبة as it appears in the ERP claims list (استلام المطالبات)."""

    id: str  # VRM-XXXXXX
    po_no: str = ""
    project_no: str = ""
    project_name_ar: str = ""
    project_name_en: str = ""
    vendor_account: str = ""
    vendor_name_ar: str = ""
    vendor_name_en: str = ""
    contract_value: float = 0.0  # base, excl. VAT — same basis as BoQ line prices
    contract_kind: ContractKind = ContractKind.works  # goods -> receipt, works -> COC
    contract_end_date: str = ""  # contractual completion/delivery date (header; falls back to the contract doc)
    claim_amount_base: float = 0.0
    vat_amount: float = 0.0
    claim_amount_total: float = 0.0  # شامل الضريبة
    invoice_no: str = ""  # vendor-entered — must match the invoice document
    payment_no: int = 0  # رقم الدفعة
    claim_type: ClaimType = ClaimType.periodic  # نوع المستخلص
    claim_date: str = ""
    cumulative_prior: float = 0.0  # disbursed on this contract before this claim (base, excl. VAT)
    prior_payment_count: int = 0
    status_ar: str = "تحت الاجراء"
    source_files: list[ClaimFile] = Field(default_factory=list)
    documents: ClaimDocuments = Field(default_factory=ClaimDocuments)
    origin: str = "erp"  # "erp" = read-only D365/mock record; "submitted" = guided intake
    # Guided-review annotations, filled at the API layer from the progress/runs
    # store (never authoritative on the ERP record itself).
    review_step: int = 0  # 0 = not started, 1-5 = at that wizard step, 6 = completed
    latest_verdict: Verdict | None = None


class QrField(BaseModel):
    """One decoded ZATCA QR field next to the value it should match.

    ``expected`` comes from the invoice face (or claim form for totals);
    ``match`` is None when there is nothing to compare against.
    """

    key: str  # seller_name | vat_number | timestamp | total | vat
    label_en: str
    label_ar: str
    value: str = ""  # decoded from the QR TLV
    expected: str = ""  # invoice-face / claim value it must match
    match: bool | None = None


class QrSummary(BaseModel):
    """Deterministic decode of the invoice QR, for the evidence panel."""

    present: bool = False
    valid_tlv: bool = False
    error: str = ""
    fields: list[QrField] = Field(default_factory=list)
    phase2_status: str = ""  # valid | pseudo | invalid_signature | absent
    phase2_problems: list[str] = Field(default_factory=list)
    phase2_notes: list[str] = Field(default_factory=list)
    has_stamp: bool = False


class Finding(BaseModel):
    rule_id: str
    gate: str
    severity: Severity
    title_en: str
    title_ar: str
    detail_en: str = ""
    detail_ar: str = ""
    source: RuleSource
    evidence: dict = Field(default_factory=dict)  # values the check compared


class GateRun(BaseModel):
    gate: str
    severity: Severity  # worst finding in the gate
    findings: list[Finding] = Field(default_factory=list)


class RunResult(BaseModel):
    claim_id: str
    gates: list[GateRun] = Field(default_factory=list)
    verdict: Verdict = Verdict.needs_human
    rationale_en: str = ""
    rationale_ar: str = ""
    # What the checks actually ran on — the extracted documents and the decoded
    # QR — so the UI can show extracted fields and link evidence to the files.
    extracted: ClaimDocuments | None = None
    qr: QrSummary | None = None
